exports.SYMBOLS = {
  "F-FA": "Fire Alarm",
  "F-EE": "Extinguishing Equipment",
  "F-ES": "Extinguishing System",
  "F-EL": "Emergency Light",
  "F-SH": "Smoke Hatche",
  "F-OI": "Other Technical Installation",
  "F-KES": "Kitchen Extinguishing System",
  "NF-EL": "Elevator",
  "NF-ES": "Escalator",
  "NF-WC": "Window Cleaner",
  "NF-SU": "Survailance",
  "NF-JA": "Janitor",
  "NF-GA": "Garderner",

  "R-ADM": "Admin",
  "R-VEN": "Vendor",
  "R-CUS": "Customer",
  "R-TEN": "Tenant",
  "R-WOR": "Worker",
  "R-NON": "None",
};
